set_temperature:
  name: Set Temperature
  description: Set the target temperature for a specific zone
  fields:
    zone_id:
      name: Zone ID
      description: The zone identifier
      required: true
      selector:
        text:
    temperature:
      name: Temperature
      description: Target temperature in Celsius
      required: true
      selector:
        number:
          min: 5
          max: 35
          step: 0.5
          unit_of_measurement: "°C"

set_hvac_mode:
  name: Set HVAC Mode
  description: Set the HVAC mode for a specific zone
  fields:
    zone_id:
      name: Zone ID
      description: The zone identifier
      required: true
      selector:
        text:
    hvac_mode:
      name: HVAC Mode
      description: The HVAC mode to set
      required: true
      selector:
        select:
          options:
            - "off"
            - "heat"
            - "cool"
            - "auto"

get_temperature_history:
  name: Get Temperature History
  description: Retrieve temperature history for a specific zone
  fields:
    zone_id:
      name: Zone ID
      description: The zone identifier
      required: true
      selector:
        text:
    hours:
      name: Hours
      description: Number of hours of history to retrieve
      required: false
      default: 24
      selector:
        number:
          min: 1
          max: 168
          step: 1
          unit_of_measurement: "hours"

export_temperature_data:
  name: Export Temperature Data
  description: Export temperature data for all zones to a CSV file
  fields:
    days:
      name: Days
      description: Number of days of data to export
      required: false
      default: 7
      selector:
        number:
          min: 1
          max: 30
          step: 1
          unit_of_measurement: "days"
    file_path:
      name: File Path
      description: Path where to save the CSV file (optional)
      required: false
      selector:
        text:
